# NumPy 

#### The basics

The numpy's main objective is the homogenous multidimensional array. It is a table of elements(usually number) all of the same type, indexed by a tuple of non-negative integer. In NumPy dimensions are called axes.

Lets take an example where a array coordinates of a point in 3D space [1, 2, 1] has one axis. Tha axis has 3 elements in it, so we say it has a lenght of 3.

[[1., 0., 0.],
 [0., 1., 2.]]

for the above array which is a 2d array which means the array as 2 axes 

`Note:` axes = dimensions of array

- axes 0 = 2(2 rows)
- axes 1 = 3(3 columns)

NumPy array class is called `ndarray`. It is also known by alias array. and `numpy.array` is not same as the standard python library class `array.array`, which only handles one dimensional arrays and offers less functionality. 

The imp attributes of `ndarray` objects are:

`ndarray.ndim` - returns the number of axes(dimensions) of the array.

`ndarray.shape` - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimensions. For a matrix with n rows and m colomns, the shape will be(m,n). The length of the `shape` tuple is therefore the number of axes, `ndim`

`ndarray.size` - it returns the total number of elements in the array which is equal to the product of the `shape` (m * n)

`ndarray.dtype` - An object describing the type of element in the array. Where on can create or specify dtype's using the standard python types

`ndarray.itemsize` - The size in of each elements in bytes which is present in array. For example, an array of elements of type `float64` has `itemsize` 8(=64/8), while one of type `complex32` has `itemsize` 4(=32/8). It is equivalent to `ndarray.dtype.itemsize`.

`ndarray.data` - The buffer containing the actual elements of the array. Normally we won't need to use this attribute because we will access the elements in an array using indexing facilities.


In [3]:
import numpy as np

a = np.arange(15).reshape(3, 5)

a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape


(3, 5)

In [5]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.size

15

In [13]:
type(a)

numpy.ndarray

In [15]:
b = np.array([1, 2, 3])
b


array([1, 2, 3])

In [17]:
b.size

3

In [18]:
b.ndim

1

In [19]:
b.shape

(3,)

#### Array creation 

There are several ways to create an array from a regular python list or tuple using `array` function. The of resulting array is deduced from the type of the elements in the sequences.


In [27]:
a = np.array([1, 3, 5])

a.dtype

dtype('int32')

In [24]:
b = np.array([1.2, 3.4, 5.6])

b.dtype

dtype('float64')

In [29]:
c = np.array([[1, 2], [3, 4]], dtype = complex) # the array dtype can also be explicity specified at the creation time

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elments of array is unknown so the numpy offers serveral functions to create initial placeholders content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, and the function `ones` creates a function full of ones and the `empty` functions creates an array whose initial content is random and depends on the state of the memory. By default, the dtype is created as float64 but can be specified using `dtype` argument

To create a sequence of numbers, NumPy provides the `arange` function which is analogous to the python built-in `range`, but returns an array.

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones((3, 2), dtype = np.int32)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [37]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.arange(10, 30, 5) # np.arange(start, end, increment)

array([10, 15, 20, 25])

In [ ]:
np.arange(15) # by defalut starts from zero

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
np.arange(4, 14) # starts from 4 and ends at 13

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [45]:
np.arange(0, 3, 0.3) # also accepts float values

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floting point percision. For this reason , it is usaully better to use the function `linspace` that recives as an argument the number of elements that we want, instead of the step

In [46]:
from numpy import pi

np.linspace(0, 2, 9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [50]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -